-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'EVENT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'NEW_APPLICANT';
ALTER TYPE "NotificationType" ADD VALUE 'VENDOR_WITHDREW';
ALTER TYPE "NotificationType" ADD VALUE 'EVENT_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_NEEDED';
